// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'currency.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

const _$CurrencyEnumMap = {
  Currency.AED: 'Emirati Dirham',
  Currency.AFN: 'Afghan Afghani',
  Currency.ALL: 'Albanian Lek',
  Currency.AMD: 'Armenian Dram',
  Currency.ANG: 'Netherlands Antillean Guilder',
  Currency.AOA: 'Angolan Kwanza',
  Currency.ARS: 'Argentinian Peso',
  Currency.AUD: 'Australian Dollar',
  Currency.AWG: 'Aruban Guilder',
  Currency.AZN: 'Azerbaijani Manat',
  Currency.BAM: 'Bosnia and Herzegovina Convertible Mark',
  Currency.BBD: 'Barbadian Dollar',
  Currency.BDT: 'Bangladeshi Taka',
  Currency.BGN: 'Bulgarian Lev',
  Currency.BHD: 'Bahraini Dinar',
  Currency.BIF: 'Burundian Franc',
  Currency.BMD: 'Bermudian Dollar',
  Currency.BND: 'Brunei Darussalam Dollar',
  Currency.BOB: 'Bolivian Bolíviano',
  Currency.BRL: 'Brazilian Real',
  Currency.BSD: 'Bahamian Dollar',
  Currency.BTN: 'Bhutanese Ngultrum',
  Currency.BWP: 'Botswana Pula',
  Currency.BYN: 'Belarusian Ruble',
  Currency.BZD: 'Belize Dollar',
  Currency.CAD: 'Canadian Dollar',
  Currency.CDF: 'Congolese Franc',
  Currency.CHF: 'Swiss Franc',
  Currency.CLF: 'Chilean Peso',
  Currency.CNY: 'Chinese Yuan Renminbi',
  Currency.COP: 'Colombiam Peso',
  Currency.CRC: 'Costa Rican Colón',
  Currency.CUP: 'Cuban Peso',
  Currency.CVE: 'Cape Verdean Escudo',
  Currency.CZK: 'Czech Koruna',
  Currency.DJF: 'Djiboutian Franc',
  Currency.DKK: 'Danish Krone',
  Currency.DOP: 'Dominican Republic Peso',
  Currency.DZD: 'Algerian Dinar',
  Currency.EGP: 'Egyptian Pound',
  Currency.ERN: 'Eritrean Nakfa',
  Currency.ETB: 'Ethiopian Birr',
  Currency.EUR: 'Euro',
  Currency.FJD: 'Fijian Dollar',
  Currency.FKP: 'Falkland Islands (Malvinas) Pound',
  Currency.GBP: 'United Kingdom Pound',
  Currency.GEL: 'Georgian Lari',
  Currency.GGP: 'Guernsey Pound',
  Currency.GHS: 'Ghanaian Cedi',
  Currency.GIP: 'Gibraltar Pound',
  Currency.GMD: 'Gambian Dalasi',
  Currency.GNF: 'Guinean Franc',
  Currency.GTQ: 'Guatemalan Quetzal',
  Currency.GYD: 'Guyanese Dollar',
  Currency.HKD: 'Hong Kong Dollar',
  Currency.HNL: 'Honduran Lempira',
  Currency.HRK: 'Croatian Kuna',
  Currency.HTG: 'Haitian Gourde',
  Currency.HUF: 'Hungarian Forint',
  Currency.IDR: 'Indonesian Rupiah',
  Currency.ILS: 'Israeli New Shekel',
  Currency.IMP: 'Manx Pound',
  Currency.INR: 'Indian Rupee',
  Currency.IQD: 'Iraqi Dinar',
  Currency.IRR: 'Iranian Rial',
  Currency.ISK: 'Icelandic Króna',
  Currency.JEP: 'Jersey Pound',
  Currency.JMD: 'Jamaican Dollar',
  Currency.JOD: 'Jordanian Dinar',
  Currency.JPY: 'Japanese Yen',
  Currency.KES: 'Kenyan Shilling',
  Currency.KGS: 'Kyrgyz Som',
  Currency.KHR: 'Cambodian Riel',
  Currency.KMF: 'Comorian Franc',
  Currency.KPW: 'North Korean Won',
  Currency.KRW: 'South Korean Won',
  Currency.KWD: 'Kuwaiti Dinar',
  Currency.KYD: 'Cayman Islands Dollar',
  Currency.KZT: 'Kazakhstani Tenge',
  Currency.LAK: 'Lao Kip',
  Currency.LBP: 'Lebanese Pound',
  Currency.LKR: 'Sri Lankan Rupee',
  Currency.LRD: 'Liberian Dollar',
  Currency.LSL: 'Lesotho Loti',
  Currency.LYD: 'Libyan Dinar',
  Currency.MAD: 'Moroccan Dirham',
  Currency.MDL: 'Moldovan Leu',
  Currency.MGA: 'Malagasy Ariary',
  Currency.MKD: 'Macedonian Denar',
  Currency.MMK: 'Myanmar Kyat',
  Currency.MNT: 'Mongolian Tughrik',
  Currency.MOP: 'Macanese Pataca',
  Currency.MRU: 'Mauritanian Ouguiya',
  Currency.MUR: 'Mauritian Rupee',
  Currency.MVR: 'Maldivian Rufiyaa',
  Currency.MWK: 'Malawian Kwacha',
  Currency.MXN: 'Mexican Peso',
  Currency.MYR: 'Malaysian Ringgit',
  Currency.MZN: 'Mozambican Metical',
  Currency.NAD: 'Namibian Dollar',
  Currency.NGN: 'Nigerian Naira',
  Currency.NIO: 'Nicaraguan Córdoba',
  Currency.NOK: 'Norwegian Krone',
  Currency.NPR: 'Nepalese Rupee',
  Currency.NZD: 'New Zealand Dollar',
  Currency.OMR: 'Omani Rial',
  Currency.PAB: 'Panamanian Balboa',
  Currency.PEN: 'Peruvian Sol',
  Currency.PGK: 'Papua New Guinean Kina',
  Currency.PHP: 'Philippine Peso',
  Currency.PKR: 'Pakistani Rupee',
  Currency.PLN: 'Polish Zloty',
  Currency.PYG: 'Paraguayan Guarani',
  Currency.QAR: 'Qatari Riyal',
  Currency.RON: 'Romanian Leu',
  Currency.RSD: 'Serbian Dinar',
  Currency.RUB: 'Russian Ruble',
  Currency.RWF: 'Rwandan Franc',
  Currency.SAR: 'Saudi Riyal',
  Currency.SBD: 'Solomon Islands Dollar',
  Currency.SCR: 'Seychellois Rupee',
  Currency.SDG: 'Sudanese Pound',
  Currency.SEK: 'Swedish Krona',
  Currency.SGD: 'Singapore Dollar',
  Currency.SHP: 'Saint Helena Pound',
  Currency.SLL: 'Sierra Leonean Leone',
  Currency.SOS: 'Somali Shilling',
  Currency.SRD: 'Surinamese Dollar',
  Currency.SSP: 'South Sudanese Pound',
  Currency.STN: 'São Tomé and Príncipe Dobra',
  Currency.SVC: 'Salvadoran Colón',
  Currency.SYP: 'Syrian Pound',
  Currency.SZL: 'Swazi Lilangeni',
  Currency.THB: 'Thai Baht',
  Currency.TJS: 'Tajikistani Somoni',
  Currency.TMT: 'Turkmenistani Manat',
  Currency.TND: 'Tunisian Dinar',
  Currency.TOP: 'Tongan Paʻanga',
  Currency.TRY: 'Turkish Lira',
  Currency.TTD: 'Trinidad and Tobago Dollar',
  Currency.TVD: 'Tuvaluan Dollar',
  Currency.TWD: 'New Taiwan Dollar',
  Currency.TZS: 'Tanzanian Shilling',
  Currency.UAH: 'Ukrainian Hryvnia',
  Currency.UGX: 'Ugandan Shilling',
  Currency.USD: 'United States Dollar',
  Currency.UYU: 'Uruguayan Peso',
  Currency.UZS: 'Uzbekistani Sum',
  Currency.VEB: 'Venezuela Bolívar',
  Currency.VED: 'Venezuelan Digital Bolívar',
  Currency.VEF: 'Venezuelan Hard Bolívar (Fuerte)',
  Currency.VES: 'Venezuelan Sovereign Bolívar (Soberano)',
  Currency.VND: 'Vietnamese Đồng',
  Currency.VUV: 'Vanuatu Vatu',
  Currency.WST: 'Samoan Tālā',
  Currency.XAF: 'Central African CFA Franc',
  Currency.XCD: 'East Caribbean Dollar',
  Currency.XOF: 'West African CFA Franc',
  Currency.XPF: 'CFP Franc',
  Currency.YER: 'Yemeni Rial',
  Currency.ZAR: 'South African Rand',
  Currency.ZMW: 'Zambian Kwacha',
  Currency.ZWD: 'Zimbabwean Dollar',
};
