targets:
  $default:
    builders:
      copy_with_extension_gen:
        enabled: true
        options:
          copy_with_null: true
      json_serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_field_map: true
          create_per_field_to_json: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true
    sources:
      - ./*
      - $package$
      - $lib$
      - $lib$/**
      - lib/**
      - pubspec.yaml
      - web/**
    dependencies:
      - autoequal
